name: navo-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - astropy>=4.1
  - matplotlib
  - requests
  - jupyterlab>=2.0
  - scipy
  - aplpy
  - pip
  - pip:
    - astroquery
    - jupyter-offlinenotebook
    - git+https://github.com/astropy/pyvo.git@c7a2ebad95629932775fb0966a6a79aec23b6dda
