name: Run CircleCI artifacts redirector, rendered pages are under Details

on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: scientific-python/circleci-artifacts-redirector-action@839631420e45a08af893032e5a5e8843bf47e8ff  # v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.NAVO_WORKSHOP_CIRCLE_TOKEN }}
          artifact-path: 0/_build/html/index.html
          circleci-jobs: build-docs